// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1s-tRmIJp1oBsHj1OZvXRRJc427BUD9A',
    appId: '1:959037542828:web:939cb23becfa8dc8f6ea09',
    messagingSenderId: '959037542828',
    projectId: 'dangdang-app',
    authDomain: 'dangdang-app.firebaseapp.com',
    storageBucket: 'dangdang-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHANhRlAN_etGgx3beKciU9AOsiIeTmVc',
    appId: '1:959037542828:android:1ac0790b66ce33d9f6ea09',
    messagingSenderId: '959037542828',
    projectId: 'dangdang-app',
    storageBucket: 'dangdang-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1s-tRmIJp1oBsHj1OZvXRRJc427BUD9A',
    appId: '1:959037542828:web:d3f4c317b7c23517f6ea09',
    messagingSenderId: '959037542828',
    projectId: 'dangdang-app',
    authDomain: 'dangdang-app.firebaseapp.com',
    storageBucket: 'dangdang-app.firebasestorage.app',
  );
}
